# Generated by Django 5.1.5 on 2025-04-06 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
