# Generated by Django 5.1.5 on 2025-04-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_playerprediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerPrediction',
        ),
    ]
