# Generated by Django 5.1.5 on 2025-04-14 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_playerprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGamePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('fixture_id', models.IntegerField()),
                ('opponent_team', models.CharField(max_length=100)),
                ('minutes', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('clean_sheets', models.BooleanField()),
                ('saves', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('penalties_saved', models.IntegerField()),
                ('penalties_missed', models.IntegerField()),
                ('position', models.CharField(max_length=20)),
                ('total_points', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player_id', 'fixture_id')},
            },
        ),
    ]
