# Generated by Django 5.1.5 on 2025-04-14 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_playergameperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerGamePerformance',
        ),
    ]
