# Generated by Django 5.1.5 on 2025-04-16 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_playergameperformance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGamePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
                ('total_goals', models.IntegerField(default=0)),
                ('total_assists', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('total_saves', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('custom_points', models.IntegerField(default=0)),
                ('forward_goals', models.IntegerField(default=0)),
                ('midfielder_goals', models.IntegerField(default=0)),
                ('defender_clean_sheets', models.IntegerField(default=0)),
                ('goalkeeper_clean_sheets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gameweek')},
            },
        ),
    ]
