# Generated by Django 5.1.5 on 2025-04-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_teamgameperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameperformance',
            name='gameweek',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
