# Generated by Django 5.1.5 on 2025-04-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_playergameperformance_gameweek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamgameperformance',
            old_name='clean_sheets',
            new_name='total_clean_sheets',
        ),
        migrations.RenameField(
            model_name='teamgameperformance',
            old_name='custom_points',
            new_name='total_points',
        ),
        migrations.RenameField(
            model_name='teamgameperformance',
            old_name='red_cards',
            new_name='total_red_cards',
        ),
        migrations.RenameField(
            model_name='teamgameperformance',
            old_name='yellow_cards',
            new_name='total_yellow_cards',
        ),
    ]
