# Generated by Django 5.1.5 on 2025-04-16 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_clean_sheets_teamgameperformance_total_clean_sheets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
                ('predicted_forward_goals', models.IntegerField(default=0)),
                ('predicted_midfielder_goals', models.IntegerField(default=0)),
                ('predicted_defender_clean_sheets', models.IntegerField(default=0)),
                ('predicted_goalkeeper_clean_sheets', models.IntegerField(default=0)),
                ('predicted_total_assists', models.IntegerField(default=0)),
                ('multiplier_applied', models.BooleanField(default=False)),
                ('prediction_correct', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gameweek')},
            },
        ),
    ]
