# Generated by Django 5.1.5 on 2025-04-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_teamprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgameperformance',
            name='final_points',
            field=models.FloatField(default=0),
        ),
    ]
