# Generated by Django 5.1.5 on 2025-04-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
