# Generated by Django 5.1.5 on 2025-05-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Cricket', 'Cricket'), ('Swimming', 'Swimming'), ('Table Tennis', 'Table Tennis'), ('Badminton', 'Badminton'), ('Volleyball', 'Volleyball'), ('Track and Field', 'Track and Field'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
