# Generated by Django 5.1.5 on 2025-05-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_userprofile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
    ]
