# Generated by Django 5.1.5 on 2025-05-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userprofile_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=6),
        ),
    ]
